version: '3.8'

services:
  mongodb:
    image: 'mongo'
    ports:
    - "27017:27017"
    env_file:
    - ./env/mongo.env
    volumes:
      - data:/data/db

  node:
    build: .
    ports:
    - "80:80"
    env_file:
    - ./env/node.env
    depends_on:
    - mongodb

volumes:
  data:
